In [1]:
import cv2
from PIL import Image
import numpy as np
from matplotlib import pyplot as plt

In [2]:
img = cv2.imread('C:/Users/Lennart Pc/Pictures/kartoffel_ (1).jpg')
img = cv2.resize(img, dsize=(256, 256), interpolation=cv2.INTER_CUBIC)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("gray",img)
ret, binary = cv2.threshold(gray, 150, 256, cv2.ADAPTIVE_THRESH_GAUSSIAN_C)
cv2.imshow("Binary image", binary)

laplacian = cv2.Laplacian(binary,cv2.CV_64F)
cv2.imshow("laplace", laplacian)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
print(img[1])

[[182 191 201]
 [183 192 201]
 [185 194 203]
 [184 195 203]
 [183 192 201]
 [185 193 202]
 [185 194 203]
 [184 193 202]
 [189 196 205]
 [189 196 205]
 [191 198 207]
 [192 198 209]
 [189 198 207]
 [191 198 207]
 [191 198 207]
 [192 199 208]
 [192 198 209]
 [190 199 208]
 [189 198 207]
 [188 197 207]
 [188 197 206]
 [192 198 209]
 [190 199 209]
 [189 198 208]
 [192 201 210]
 [189 198 207]
 [190 199 208]
 [193 202 211]
 [192 199 208]
 [193 200 209]
 [194 201 210]
 [196 203 212]
 [195 202 211]
 [195 202 211]
 [193 202 211]
 [193 200 209]
 [194 201 210]
 [196 203 212]
 [196 203 212]
 [193 200 209]
 [194 203 212]
 [197 204 213]
 [196 203 212]
 [198 205 214]
 [197 204 213]
 [197 204 213]
 [196 203 212]
 [196 203 212]
 [196 203 212]
 [196 203 212]
 [195 202 211]
 [195 202 211]
 [195 202 211]
 [196 203 212]
 [197 204 213]
 [196 203 212]
 [198 205 214]
 [196 203 212]
 [196 203 212]
 [198 205 214]
 [197 204 213]
 [198 205 214]
 [198 205 214]
 [198 205 214]
 [198 205 214]
 [198 205 214]
 [197 204 

In [4]:

for i in range(len(laplacian)):
    for j in range(len(laplacian[0])):
    
        if laplacian[i][j]!= 0.0:
            marks=marks+(i,j,laplacian[i][j])
    
print(marks)

NameError: name 'marks' is not defined

In [ ]:
im2, contours, hierarchy = cv2.findContours(binary, 1, 2, )
cnt = contours[0]
rect = cv2.minAreaRect(cnt)
box = cv2.boxPoints(rect)
box = np.int0(box)
cv2.drawContours(img,[box],0,(0,0,255),2)

error: OpenCV(4.8.1) :-1: error: (-5:Bad argument) in function 'findContours'
> Overload resolution failed:
>  - Can't parse 'contours'. Input argument doesn't provide sequence protocol
>  - Can't parse 'contours'. Input argument doesn't provide sequence protocol
