In [9]:
import cv2
from PIL import Image
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.image as mpimg
from matplotlib import colors

In [10]:
img = cv2.imread('C:/Users/Lennart Pc/Pictures/karotte/karotte_100.jpg')
img = cv2.resize(img, dsize=(256, 256), interpolation=cv2.INTER_CUBIC)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("original",img)
ret, binary = cv2.threshold(gray, 50, 200, cv2.ADAPTIVE_THRESH_GAUSSIAN_C)
cv2.imshow("Binary image", binary)

laplacian = cv2.Laplacian(binary,cv2.CV_64F)
cv2.imshow("laplace", laplacian)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
#Schwarzer Hintergrnd
blank_image = np.zeros((256,256,3), np.uint8)
for i in range(len(binary)):
    for j in range(len(binary[i])):
        if binary[i][j] !=0:
            blank_image[i][j]=img[i][j]

cv2.imshow("Black backround",blank_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
y=0
x=0
w=255
h=255
counter=0
index_object=0
#Bilder einlesen

Adresse="C:/Users/Lennart Pc/Pictures/karotte/karotte_"+str(40)+".jpg"
img = cv2.imread(Adresse)
img = cv2.resize(img, dsize=(256, 256), interpolation=cv2.INTER_CUBIC)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, binary = cv2.threshold(gray, 150, 156, cv2.ADAPTIVE_THRESH_GAUSSIAN_C)
laplacian = cv2.Laplacian(binary,cv2.CV_64F)


for i in range(len(laplacian)):
    for j in range(len(laplacian)):
        if laplacian[i][j]!= 0.0 and y==0:
            y=i
            index_object=1
        
        if laplacian[i][j]==0.0 and index_object==1:
            counter=counter+1
    

    if counter == 256 and index_object==1:
        h=i
        index_object=0
        
    else:
        counter=0
        
counter=0

            
        

for i in range(len(laplacian)):
    for j in range(len(laplacian)):
        if laplacian[j][i]!= 0.0 and x==0:
            x=i
            index_object=1
        if laplacian[j][i]==0.0 and index_object==1:
            counter=counter+1

    if counter == 256 and index_object==1:
        w=i
        index_object=0
        
    else:
        counter=0
            
print(x,y,w,h)
img = cv2.rectangle(img,(x,y),(w,h),(0,255,0),1)
cv2.imshow("Black backround",img)
cv2.imshow("Binary", binary)
cv2.imshow("laplacian image", laplacian)
cv2.waitKey(00)
cv2.destroyAllWindows()

92 71 158 169


In [13]:
contour, hierarchy = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
#Boundingbox mit min Inhalt
for i in range(len(contour)):

    con=contour[i]
    print(con)
    rect = cv2.minAreaRect(con)
    box = cv2.boxPoints(rect)
    box = np.int0(box)
    cv2.drawContours(img,[box],0,(0,0,255),1)
print(len(contour))

#elipse
#ellipse = cv2.fitEllipse(con)
#cv2.ellipse(img,ellipse,(0,255,0),2)

#show images
cv2.imshow("Binary image", img)
cv2.waitKey(00)
cv2.destroyAllWindows()


[[[127  72]]

 [[126  73]]

 [[122  73]]

 [[121  74]]

 [[119  74]]

 [[118  75]]

 [[117  75]]

 [[116  76]]

 [[115  76]]

 [[107  84]]

 [[107  85]]

 [[105  87]]

 [[105  88]]

 [[104  89]]

 [[104  90]]

 [[103  91]]

 [[103  92]]

 [[102  93]]

 [[102  95]]

 [[101  96]]

 [[101  98]]

 [[100  99]]

 [[100 101]]

 [[ 99 102]]

 [[ 99 109]]

 [[ 98 110]]

 [[ 99 111]]

 [[ 99 121]]

 [[100 122]]

 [[100 125]]

 [[101 126]]

 [[101 127]]

 [[102 128]]

 [[102 130]]

 [[103 131]]

 [[103 134]]

 [[105 136]]

 [[105 141]]

 [[104 142]]

 [[104 143]]

 [[100 147]]

 [[100 149]]

 [[ 99 150]]

 [[ 98 149]]

 [[ 96 149]]

 [[ 95 148]]

 [[ 94 149]]

 [[ 93 148]]

 [[ 93 151]]

 [[ 94 150]]

 [[ 95 150]]

 [[ 96 151]]

 [[ 97 151]]

 [[ 97 150]]

 [[ 98 149]]

 [[ 99 150]]

 [[ 99 152]]

 [[100 153]]

 [[100 155]]

 [[101 156]]

 [[101 157]]

 [[104 160]]

 [[105 160]]

 [[106 161]]

 [[108 161]]

 [[109 162]]

 [[110 162]]

 [[112 164]]

 [[114 164]]

 [[115 165]]

 [[116 165]]

 [[117

C:\Users\Lennart Pc\AppData\Local\Temp\ipykernel_11556\3759681939.py:9: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  box = np.int0(box)


In [15]:
#Boundingbox in Ordner einzeichnen
for i in range(28,200):
    #Bilder einlesen
    Adresse="C:/Users/Lennart Pc/Pictures/karotte/karotte_"+str(i)+".jpg"
    img = cv2.imread(Adresse)
    img = cv2.resize(img, dsize=(256, 256), interpolation=cv2.INTER_CUBIC)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, binary = cv2.threshold(gray, 150, 156, cv2.ADAPTIVE_THRESH_GAUSSIAN_C)
    laplacian = cv2.Laplacian(binary,cv2.CV_64F)
    con_area=[]
    
    #Konturen finden
    contour, hierarchy = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    #größte Kontur ausfiltern
    for j in range(len(contour)):
        con_area.append(cv2.contourArea(contour[j]))
   
    max_area= np.max(con_area)

    
    #Kontur einzeichnen
    con=contour[con_area.index(max_area)]
    
    rect = cv2.minAreaRect(con)
    box = cv2.boxPoints(rect)
    box = np.intp(box)
    cv2.drawContours(img,[box],0,(0,0,255),1)
    saveadresse="C:/Users/Lennart Pc/Pictures/karotte_alleboxen/karotte_mitBox"+str(i)+".jpg"
    cv2.imwrite(saveadresse,img,)
    